### ISSUE TITLE
Fizzbuzz

### ISSUE THREAD

**Issue by sakshamarora1** [Developer-Students-Club-MAIT/cool_code_snippets#15]
# Description

A program that prints each number from 1 to 100 on a new line. But, for each multiple of 3, print `Fizz` instead of the number. For each multiple of 5, print `Buzz` instead of the number. For numbers which are multiples of both 3 and 5, print `FizzBuzz` instead of the number.

## Language

- [x] C++
- [x] Java
- [x] Python
- [ ] Other (Please specify)

## Type of issue

- [x] Feature
- [ ] Bug

The checklist will be updated by the maintainers / author of this issue according to the language in which snippets are added or are proposed to be added.

**Comment by deeptiKalasapura** [comment]
please assign this to me

**Comment by ItIsUday** [comment]
Hey, can you assign it to me? I'd like to use python.

**Comment by demonslayer99** [comment]
assign it to me for c++

**Comment by manishita24** [comment]
Please assign it to me for java.

**Comment by sakshamarora1** [comment]
@ItIsUday @manishita24 @demonslayer99 Go ahead guys! Make sure to take care of the code quality and don't forget to read the contributing guidelines! :D
