### ISSUE TITLE
Caesar Cipher

### ISSUE THREAD

**Issue by sakshamarora1** [Developer-Students-Club-MAIT/cool_code_snippets#17]
# Description

Implement a Caesar cipher, both encoding and decoding. The key is an integer from -25 to 25. This cipher rotates the letters of the alphabet (a-z/A-Z). The script should have both functions `encode` and `decode` and the output should first encode the input message according to the key provided in the input and then decode it to demonstrate both the functions.

### Example:
```
If the message is: "Hi, How are you?" and key is: -17

encode(message) should output: "Qr, Qxf jan hxd?"

and decode(secret_message) should output: "Hi, How are you?" for secret_message="Qr, Qxf jan hxd?"
```

## Language

- [x] C++: @ShivamPorwal02 
- [ ] Java: @
- [ ] Python: @
- [ ] C: @
- [ ] Other (Please specify)

## Type of issue

- [x] Feature
- [ ] Bug

The checklist will be updated by the maintainers / author of this issue according to the language in which snippets are added or are proposed to be added.

**Comment by aolaria** [comment]
Hi, can I do it in Python?

**Comment by sakshamarora1** [comment]
@aolaria Yes, go ahead. Make sure to take care of the code quality and don't forget to read the contributing guidelines! :D

**Comment by kaustubhgupta** [comment]
@aolaria Are you working on this?

**Comment by ShivamPorwal02** [comment]
Can i take this in c++?

**Comment by aolaria** [comment]
@kaustubhgupta Hey, sorry I know that you were waiting for this, I wasn't available to use my computer for some days, I'm really sorry, I've already made an PR for this made using python.
