### ISSUE TITLE
Diamond Square!

### ISSUE THREAD

**Issue by kaustubhgupta** [Developer-Students-Club-MAIT/cool_code_snippets#22]
# Description

In this challenge, you need to create a program to print a diamond enclosed in a square. The diamond should look like this:
![image](https://user-images.githubusercontent.com/43691873/95987270-cfb14b80-0e44-11eb-9e95-a0ba01e508a0.png)

You need to take input for the number of rows

## Language

- [x] C++: @AasthaVarma, @SrijitaSarkar99 
- [x] Java: @Bhaswati-Saha 
- [x] Python: @BirajCoder
- [x] C: @arnab031
- [x] Javascript

## Type of issue

- [x] Feature
- [ ] Bug

The checklist will be updated by the maintainers/author of this issue according to the language in which snippets are added or are proposed to be added.

**Comment by BirajCoder** [comment]
Hey, I can solve this in python , can you please assign me to this issue?

**Comment by Bhaswati-Saha** [comment]
Would like to solve it in java.Can you please assign it to me?

**Comment by BirajCoder** [comment]
@kaustubhgupta  Hey , I have uploaded my code in python , please do check it and let me know if there is any error .

**Comment by arnab031** [comment]
Hello, I can solve this in C , Can you please assign me to this issue?
![Screenshot 2020-10-18 202649](https://user-images.githubusercontent.com/51916075/96371648-466d8200-1180-11eb-8031-009b53b57a35.jpg)

**Comment by sakshamarora1** [comment]
@arnab031 go ahead! Make sure to add it in `snippets/c/`.
