### ISSUE TITLE
Dictionary using Trie

### ISSUE THREAD

**Issue by deepika-rana** [Developer-Students-Club-MAIT/cool_code_snippets#24]
# Description

Implement a dictionary using a [trie](https://www.hackerearth.com/practice/data-structures/advanced-data-structures/trie-keyword-tree/tutorial/) in which the user enters a word, if it is present in the prebuilt dictionary print its meaning/definition. The user should also be able to include words of his/her own choice in the  #dictionar.

## Required prebuilt words
- hacktoberfest
- git
- open-source
- issue
- contribution

## Language
- [x] C++: @dwij2212 
- [x] Java
- [x] Python: @arnab031

## Type of issue

- [x] Feature
- [ ] Bug

The checklist will be updated by the maintainers/author of this issue according to the language in which snippets are added or are proposed to be added.

**Comment by dwij2212** [comment]
Can you assign this to me in C++ or Python? C++ preferred over python.

**Comment by arnab031** [comment]
Can you assign me this problem in Python?
