### ISSUE TITLE
Longest Common Subsequence

### ISSUE THREAD

**Issue by kaustubhgupta** [Developer-Students-Club-MAIT/cool_code_snippets#3]
# Description

Write a program to find the longest common subsequence of a string.

## Language

- [x] C++: @SrijitaSarkar99 
- [x] Java: @Bhaswati-Saha
- [x] Python: @ShivamPorwal02 

## Type of issue

- [x] Feature
- [ ] Bug

**Comment by ShivamPorwal02** [comment]
@kaustubhgupta  Can I do this in python?

**Comment by kaustubhgupta** [comment]
@ShivamPorwal02 go ahead! make sure to have a look at contribution guidelines to avoid PR rejection!

**Comment by ShivamPorwal02** [comment]
@kaustubhgupta Are you sure it is **least** not **longest** ?

**Comment by kaustubhgupta** [comment]
@ShivamPorwal02 apologies! Typing error!

**Comment by Bhaswati-Saha** [comment]
I would like to do this in Java.So please assign it to me.

**Comment by SrijitaSarkar99** [comment]
Can I solve this in C++?

**Comment by kaustubhgupta** [comment]
@SrijitaSarkar99 sure!

**Comment by Rishit19** [comment]
@ShivamPorwal02 , I would like to do this in python. Please assign me this issue.
