### ISSUE TITLE
Frequency of Characters

### ISSUE THREAD

**Issue by kaustubhgupta** [Developer-Students-Club-MAIT/cool_code_snippets#4]
# Description

Write a program to find the frequency of unique characters in a string and store the result in a text file.

## Language

- [x] C++: @ShivamPorwal02 

## Type of issue

- [x] Feature
- [ ] Bug

**Comment by yogeshsingh101200** [comment]
I can do this. can you assign it to me?

**Comment by kaustubhgupta** [comment]
@yogeshsingh101200 Language preference?

**Comment by yogeshsingh101200** [comment]
@kaustubhgupta python

**Comment by kaustubhgupta** [comment]
@yogeshsingh101200 go ahead! make sure to have a look at contribution guidelines to avoid PR rejection!

**Comment by yogeshsingh101200** [comment]
@kaustubhgupta  Sure :+1:

**Comment by YashSaxena9** [comment]
I can do it in Java and C++. Assign me too if possible :)

**Comment by sakshamarora1** [comment]
@YashSaxena9 Sure. Remember to follow the Contributing Guidelines!

**Comment by ghost** [comment]
May I do this in TypeScript?

**Comment by kaustubhgupta** [comment]
This issue is up for C++

**Comment by ShivamPorwal02** [comment]
Can i take this in c++ @kaustubhgupta

**Comment by kaustubhgupta** [comment]
assigned @ShivamPorwal02 !

**Comment by Adithanvijayan** [comment]
@kaustubhgupta Can I take this in C language

**Comment by Adithanvijayan** [comment]
@kaustubhgupta @sakshamarora1 I have created a pull request for frequency of characters in C
