### ISSUE TITLE
Flames Game

### ISSUE THREAD

**Issue by kaustubhgupta** [Developer-Students-Club-MAIT/cool_code_snippets#5]
# Description

This is a fun game. Come up with a program that displays the relationship between two persons. Read more about it [here](https://www.wikihow.com/Play-%22Flame%22)

## Language

- [x] C++
- [x] Java: @Bhaswati-Saha
- [x] Python: @silentwraith6 

## Type of issue

- [x] Feature
- [ ] Bug

**Comment by silentwraith6** [comment]
I would like to contribute in python

**Comment by kaustubhgupta** [comment]
@silentwraith6  go ahead! make sure to have a look at contribution guidelines to avoid PR rejection!

**Comment by kaustubhgupta** [comment]
This issue is up for Java and C++

**Comment by Bhaswati-Saha** [comment]
I want to do this in Java

**Comment by Bhaswati-Saha** [comment]
@kaustubhgupta I want to contribute this in Java.Please assign it to me.
